str = 'Hello World'
print('Testing a String')
print('-' * 20)
print('str', str)
str.startswith('H')
print(str.startswith('h'))
print(str.endswith('d'))
print(str.istitle())
print(str.isupper())
print(str.islower())
print(str.isalpha())

print(str.upper())
print(str.lower())
print(str.title())
print(str.swapcase())
print("     xyz     ".strip())
